### ISSUE TITLE
Asterisk 16.13.0 patch

### ISSUE THREAD

**Issue by tgreer** [usecallmanagernz/patches#1]
Asterisk 16.13.0 is available in the repos now and updated machines are now running this version. Is it possible to get a suitable patch?

Thanks

**Comment by gareth-palmer** [comment]
I missed the release of 16.13 and by the time I noticed it the -rc for 16.14 was announced so I thought I would wait for that.

It has been a while since that announcement (3 September), if that doesn't happen before October I will make a 16.13 release.

**Comment by gareth-palmer** [comment]
Patches for 13.36 and 16.13 have been added.
