### ISSUE TITLE
Phone compatibility

### ISSUE THREAD

**Issue by sioux1977** [usecallmanagernz/patches#13]
Hi All, witch phone model or series are supported with this patch? I have tested 78xx series that works quite well... does anyone know if 79xx series is supported? There is any list of supported phones series (maybe on website)?

**Comment by gareth-palmer** [comment]
The 7900 series is supported are are the 6900, 8800, 894x and 9900 series.

If the phone uses CUCM is should work with the patch for almost all of it's features, eg: the new 8900 series.

It doesn't list that information on the website, but it probably should. I will add a note on that soon.
