### ISSUE TITLE
 handle_notify_dialog: Unknown peer '9'

### ISSUE THREAD

**Issue by darkpenguin23** [usecallmanagernz/patches#4]
Hello Mr Palmer,
as an IT student i enjoy your patch a lot so i can tinker around with old SIP phones for education.
I resolved most of the problems I had over the last year and enjoy most of the functionalities the patch delivers.
But theire is one issue i can not resolve yet:
One of my phones a 9951 gives the following error messages when i pick up the handset:
**`chan_sip.c:XXXXX handle_notify_dialog: Unknown peer '9'`**
this is weired as i never specified this peer.
The phone peername is = 9943
I believe their is a REGEXP problem some where but i am not sure, tried to compile libxml2 with various settings.
Do you have any hints?
I saw from the discussion on jira thas some user had the samme issue, this comment:

Boris P. Korzun added a comment - 22/Jul/19 8:26 PM

Did you resolve this problem?
Any Hints apreciated.

Regards

Yaron Borohov

**Comment by gareth-palmer** [comment]
Hello,

Unfortunately I don't know of a way to fix the issue. I am not able to reproduce the issue on either the 7900 or 8800 series firmware and I don't have either a 8900 or 9900 series phone to test.

Gareth
