### ISSUE TITLE
Patch got stuck

### ISSUE THREAD

**Issue by rcxaemerich** [usecallmanagernz/patches#5]
Trying to apply the cisco-usecallmanager-13.38.2.patch and it hangs.
Tried to leave it "working" for more than 8 hours and nothing happens.

**Comment by gareth-palmer** [comment]
If you re-compile with DONT_OPTIMIZE and get a backtrace using gdb (ie: `bt full`), that might show what function is stuck.

Otherwise, the 13.38.2 patch is very old and has not received any testing in years. You might be better off upgrading to the latest version 18 patch.
