### ISSUE TITLE
Answer call request doesn't work on Cisco CP-7945G

### ISSUE THREAD

**Issue by sawik-PL** [usecallmanagernz/patches#7]
Simply: doesn't work and the patch attached fixes the issue.

Btw: the whole thing is really great job! Big thank you!

[dialogid-patch.txt](https://github.com/usecallmanagernz/patches/files/12513853/dialogid-patch.txt)

**Comment by gareth-palmer** [comment]
Thank-you for the contribution. Your fix has been included in the 18.19.0 patch.
